### PR TITLE
CEG-559 : Arbitrum Gas Station

### PR DESCRIPTION
**Pull request by feliciacx0**
- Remove Gas Station for Arbitrum, since Arbitrum does NOT use priority fees (re: https://developer.arbitrum.io/faqs/gas-faqs). It was override the gas price as "0" and causing all transactions to fail 

- If gasStation is `null`, we default to just using the normal method call (which works for arbitrum)

### CODE REVIEW

**Review by vsai — DISMISSED** [review]
just delete the arbitrum gas station.

Don't make all the sdk changes. Should be able to just use the default `GasStation` in which case it wouldn't be "null" and we don't need to add the `if (this.gasStation)` check for each write.

**Review by vsai — CHANGES_REQUESTED** [review]
see comment above.

we shouldn't need to make GasStation an optional / possibly null option.

just use the default gas station which would use the default empty values

**Comment by feliciacx0** [comment]
the default gas station actually doesn't work - vic and i tested different gas stations in `cega-client` and realized that none of them worked (re: https://linear.app/cega/issue/CEG-559/arbgasstation-not-working ) 

the solution that worked when i was debugging was just not having a gas station at all

**Review by vizhang — CHANGES_REQUESTED** [review]
Change not needed, the root-cause issue with deposits since the root-cause is gasLimit which was a setting on the FE side. Can continue to use existing GasStation() as is

**Pull request closed without merging**
